pipeline {
    agent any
    stages {
        stage("Checkout code") {
            steps {
                checkout scm
            }
        }
        stage("Build and Publish") {
            steps {
                //sh "cd  samples/bookinfo"
                //sh "pwd"
                //sh "ls"
                sh "./samples/bookinfo/build_push_update_images.sh ${env.BUILD_ID} --prefix=nitinp9"
            }
        }       
        stage('Deploy') {
            steps{
                sh "kubectl apply -f platform/kube/bookinfo.yaml"
            }
        }
    }    
}
