pipeline {
    agent any
    stages {
        stage("Checkout code") {
            steps {
                snDevOpsStep()
                checkout scm
            }
        }
        stage("Build and Publish") {
            steps {
                snDevOpsStep()
                sh "./samples/bookinfo/build_push_update_images.sh ${env.BUILD_ID} --prefix=nitinp9"
		snDevOpsArtifact(artifactsPayload: """{"artifacts": [{"name": "bookinfo", "version": "1.${env.BUILD_NUMBER}","semanticVersion": "1.${env.BUILD_NUMBER}.0","repositoryName": "np-dockerhub"}]}""")
            }
        }       
        stage('Deploy') {
            steps{
                snDevOpsStep()
		curl -d '{"name":"bookinfo-${env.BUILD_NUMBER}", "pipelineName" : "istio-bookinfo", "stageName":"Deploy"}' -H "Content-Type: application/json" -X POST https://tarundevopsorlando.service-now.com/api/now/cmdb/app_service/create_manual --user 'admin':'DevOps1!'
		snDevOpsChange()
                sh "kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml"
            }
        }
    }    
}
