pipeline {
    agent any
    stages {
        stage("Checkout code") {
            steps {
                snDevOpsStep()
                checkout scm
            }
        }
        stage("Build and Publish") {
            steps {
                snDevOpsStep()
                sh "./samples/bookinfo/build_push_update_images.sh ${env.BUILD_ID} --prefix=nitinp9"
            }
        }       
        stage('Deploy') {
            steps{
                snDevOpsStep()
				snDevOpsChange()
                sh "kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml"
            }
        }
    }    
}
